### ISSUE TITLE
Should mention ECMA-262

### ISSUE THREAD

**Issue by iddan** [tc39/tc39.github.io#1]
It should be explicitly mentioned that the spec is called ECMA-262 with a proper link.

**Comment by codehag** [comment]
sounds good, I think there are a couple of issues with wording -- feel free to make changes!

**Comment by codehag** [comment]
we can put this under resources! i am copying this over from [dan's feedback](https://github.com/codehag/tc39-web-draft/issues/13):

- [ ] add ecma262 and 402 under resources

**Comment by allenwb** [comment]
In fact, TC39 defines multiple standards relating to ECMAScript. Currently ECMA-262, ECMA-402, ECMA-404, ECMA-415.  Additional ones might make sense in the future.
