### ISSUE TITLE
Investigate Frontend Architecture and code quality standards

### ISSUE THREAD

**Issue by codehag** [tc39/tc39.github.io#10]
How do we want to work together on this?
Using BEM and ITCSS or something else?

**Comment by zoepage** [comment]
I'm a big fan of OOCSS and components, but am not set on this. I'm happy with everything that makes it easier for everyone to work on it. :)

**Comment by iddan** [comment]
I get along just fine with BEM. Previously used styled-components, CSS Modules and all was good as well

**Comment by codehag** [comment]
closing this because it is too broad and we should narrow our focus a bit more
