### ISSUE TITLE
Proposal Summary Table Layout

### ISSUE THREAD

**Issue by codehag** [tc39/tc39.github.io#11]
We are discussing what the table layout below the fold should look like. Here are some early thoughts:

## Table layout - new columns for current implementations

A commonly requested feature was a page that tracked the current status of where a proposal was in terms of being implemented. We have this partially finished with the proposals md, but there is more information that was requested. For example, a caniuse breakdown browser by browser of where features were available natively. 

Perhaps a table with: 
- the proposal, 
- the authors and champions, 
- the current stage, and 
- the implementation status

Combine babel and the rest of the browsers status 

- How do we do this? Do they have apis? Investigation time!
- (Chrome)[https://www.chromestatus.com/features#javascript]
- (Firefox)[ https://platform-status.mozilla.org/ ]
- (Edge)[ https://developer.microsoft.com/en-us/microsoft-edge/platform/status/ ]
- (Babel)[ https://github.com/babel/proposals -
- How do we keep maintenance down? Are there apis we can use, what resources can we rely on?

Text content 
is it what we need, do we need more information?

Design Questions
Icons -- these don’t look great, what can we do to make it better?
How do we improve readability? (suggestion, alternating background colors in the table)

**Comment by zoepage** [comment]
> the proposal,
   the authors and champions,
   the current stage, and
   the implementation status

Those sound like really good ideas. I like it!

> Combine babel and the rest of the browsers status

Could you explain a little bit more what you mean by that? Probably I am missing context. :)

> Icons -- these don’t look great, what can we do to make it better?

Do you mean the size of the emojis by that (as they are distorted) or the emojis in general?

> How do we improve readability? (suggestion, alternating background colors in the table)

+1 on alternating backgrounds. 

Other suggestion:
- Adding a grid to the tables would make them look "calmer". 
- White (#F1F1F1) background in general.
- Dismiss border of table. Just use for rows / cols.

**Comment by littledan** [comment]
Enumerating implementations can be complicated. We don't want to make anyone who does work to support new JS features feel like they're not a valued stakeholder here (they really are valued, and this website can help show that!). At the least, there needs to be a process where anyone can call themselves an implementation and get added to the list. Some other "implementations" that come to mind:
- Other transpilers
  - TypeScript (often ships Stage 3 features and develops pre-Stage 3 features behind a flag)
  - Closure compiler
  - regexp-tree (for RegExp features; integrates with Babel)
  - regenerator (for generator features; integrates with Babel)
- Other native implementations
  - Duktape
  - es6draft (@anba's reference implementation)
  - Moddable
  - Rhino, or is it dead?
- Polyfills (for standard library features)
  - core.js
  - es-shim
  - Intl.js (for ECMA-402)
- Tools
  - acorn
  - esprima
  - Flow (parses and passes through new language features)
  - Syntax highlighting from various editors
  - Minimizers, obfuscators, etc...

If you want to name JS engines by the browser they are embedded in, then Node versions should be included as well. An alternative is to just name things by the JS engine inside. (Node and browsers don't implement JS; they use JS implementations, but this distinction is often lost on the community.)

**Comment by codehag** [comment]
right, im also thinking if we really want something like this http://kangax.github.io/compat-table/es2016plus/

or if we want something more approachable. I think the example of how chrome, google and edge do their feature sites is quite good. here is chrome's as an example, https://www.chromestatus.com/features

I like that it expands and has more information, and just a quick overview otherwise

**Comment by codehag** [comment]
Sven and Jase have done some great work, we now have a place where we can add data as needed! https://github.com/tc39/tc39-web-draft/pull/21
https://github.com/tc39/tc39-web-draft/pull/33

https://github.com/tc39/tc39-web-draft/blob/master/_data/stage3.yml

So, per the requirements of this issue, we are about half way there, we are just missing the implementations. 

I would propose scaling back the scope of this issue and closing it, in favor of opening a new issue to address this specifically. Thoughts on this?

**Comment by chicoxyzzy** [comment]
> Rhino, or is it dead?

Yes it is. Rhino was replaced by Nashorn (since JDK 8) which is also [deprecated](https://bugs.java.com/view_bug.do?bug_id=JDK-8202786) now. [GraalJS](https://github.com/graalvm/graaljs) should replace them both.

**Comment by chicoxyzzy** [comment]
> right, im also thinking if we really want something like this http://kangax.github.io/compat-table/es2016plus/
> 
> or if we want something more approachable. I think the example of how chrome, google and edge do their feature sites is quite good. here is chrome's as an example, https://www.chromestatus.com/features
> 
> I like that it expands and has more information, and just a quick overview otherwise

MDN has some data on [features support by browsers](https://github.com/mdn/browser-compat-data). IMO it will be good for both MDN and this project if TC39 website will use data from MDN and contribute back to it.

**Comment by codehag** [comment]
Lets move the implementations issue into its own issue
