### ISSUE TITLE
It was unclear to me that the title of the proposal in the list was clickable

### ISSUE THREAD

**Issue by abumalick** [tc39/tc39.github.io#128]
A small UX problem:

It was unclear to me that the title of the proposal in the list was clickable

![image](https://user-images.githubusercontent.com/8377185/54364566-0a4d7380-4665-11e9-8439-239790fe99a2.png)

Maybe we can underline it to make it clear that it is a link.

I think this is very important to make it visible, because the information from the linked page is the most valuable information about the proposal.

Thanks for working to make javascript better 👍

**Comment by rkirsling** [comment]
Otherwise maybe we could add a hover color?

**Comment by abumalick** [comment]
The problem happened for me on mobile, hover wouldn't help. It has to be very clear that it is clickable.

If you prefer, you could add a button `View proposal repository` or something like this. 

There is also the wikipedia solution: 
![image](https://user-images.githubusercontent.com/8377185/54391389-99c24900-469c-11e9-89f7-aabf1193d877.png)

**Comment by ljharb** [comment]
Making it clear it’s a link is good; I’m not sure the external link pattern is particularly helpful.

**Comment by rkirsling** [comment]
Hmm, I didn't realize when looking on my phone a bit ago that this applies to _all_ links on _all_ platforms, _except_ when the link is on the same domain (thus making a surprising distinction of `tc39.github.io` from `github.com/tc39`).

I think I was expecting all _non-underlined_ links _regardless_ of target but _only_ on mobile? 🤔

**Comment by codehag** [comment]
I will revert it for now. We can address this later since it looks like it needs more discussion.
