### ISSUE TITLE
Feedback on page organization skeleton

### ISSUE THREAD

**Issue by littledan** [tc39/tc39.github.io#13]
From the menu, I see some ideas for the organization of pages. For the most part, I really like this organization; I just have a few suggested tweaks:
- I don't really understand the difference between "contributing" and "guides"; maybe they should be merged
- The survey data shows that many people want to give feedback on proposals rather than champion their own. Let's see if we can organize the website this way; "championing your first proposal" sounds like a really inviting title, as if everyone champions proposals; maybe this should be just "proposal guidelines"
- I'm not sure if "running the tests" is a common path; this is a setup that happens once per implementation. Maybe you mean "contributing tests" (as you have in the contributing section)
- I don't think we have a programme of work :(
- For "archive", I'm not sure if it's useful to link to those old versions; maybe we could just have one link to the Ecma page in general
- For the current specification, link to the current *draft* specification on GitHub (and call it out as a draft), rather than the previous annual specification.
- I'm not sure if we should paste the set of current proposals on the homepage. It seems like many people are already scared because they think they should understand all of the proposals to contribute (which is completely not the case; no one understands all of them). It might be better to leave it on a separate page, either in its current location in the proposals repo or a prettier version of it in a separate page on the new site
- For "process", I think we should write a page which is a more approachable, high-level introduction, as well as case studies for how other proposals have gone through the process
- There should be some link to the ecma262 and ecma402 repositories, which are where a lot of the work happens (maybe under resources?)
- For "who", I'd focus less on the formal Ecma structure and more on how TC39 attendees include so many important stakeholders

**Comment by zoepage** [comment]
@littledan Just for context: 
There is a draft for an updated information architecture.

https://github.com/codehag/tc39-web-draft/issues/12#issue-314584616
https://github.com/codehag/tc39-web-draft/issues/11#issue-314172414
https://github.com/codehag/tc39-web-draft/issues/5#issuecomment-381546845

**Comment by codehag** [comment]
This is really great. I want to summarize a bit o what I am reading here into pieces that can be done: 

we need to update the content: 
- [x] program of work is outdated
- [x] current spec should point to the github draft not the 
- [x] add ecma262 and 402 under resources
- [x] replace archive with a link to the Ecma page in general

for the other parts you mentioned, we will need to flesh them out more. I will add them to the agenda for our meeting today

**Comment by codehag** [comment]
@littledan its been a while but I think this might be resolved?
