### ISSUE TITLE
Incorrect "Who" info

### ISSUE THREAD

**Issue by allenwb** [tc39/tc39.github.io#14]
The official name of the standards organization that TC39 is part of is now  "Ecma International".  They no longer used the all caps "ECMA" (except in document id's like ECMA-262) and no longer consider "Ecma" to be an acronym for "European Computer Manufactures Association".

For more history of the name see https://www.ecma-international.org/memento/history.htm

Keep in mind that TC39 is not a standalone organization and its authority to create standards comes from Ecma. There really should be a link back to the main Ecma website and and probably a statement that organizations that want to participate in the ECMAScript standardization process need to become Ecma members

**Comment by codehag** [comment]
This has been resolved
