### ISSUE TITLE
Repository link specifies http://, but site lacks redirect to HTTPS

### ISSUE THREAD

**Issue by strogonoff** [tc39/tc39.github.io#144]
I recommend to set up HTTP &rarr; HTTPS redirect (CloudFront has a distribution option that does it), in meantime you could change protocol in repository link to `https://…`.

**Comment by strogonoff** [comment]
Local issue—can’t reproduce on another device, redirects are fine.

**Comment by littledan** [comment]
Well, we should change the links to https anyway. PRs welcome.

**Comment by xtuc** [comment]
cc @othree who just made https://github.com/tc39/tc39.github.io/issues/144, do you think there are other links we could change?
