### ISSUE TITLE
mobile menu toggling

### ISSUE THREAD

**Issue by Alexits93** [tc39/tc39.github.io#146]
- the mobile menu can not be toggled (Samsung Galaxy S7 edge)
- the mobile menu points can not be toggled. (Samsung Galaxy S7 edge and Chrome dev. tools)
-  only interactive when clicking on arrow, the menu text does nothing
- the end of the mobile menu can not be seen clearly when end on white background
- sometimes the mobile menu does not expand with the opened menu points

![Annotation 2019-03-22 090337](https://user-images.githubusercontent.com/25954992/54808860-c1f40e00-4c81-11e9-9721-e5743b78a20c.png)

**Comment by codehag** [comment]
Thanks for the report!
