### ISSUE TITLE
no way to activate "Show Example" using keyboard navigation

### ISSUE THREAD

**Issue by michaelficarra** [tc39/tc39.github.io#147]
I can't figure out how someone navigating only via keyboard (or I'm assuming screen reader) would show or hide the examples. You can't tab to it since it's just a `<div>`, and even if you could, it can't be activated with the keyboard. I think this will cause accessibility issues.

This may be addressed by replacing the "show example" feature with something else, as in https://github.com/tc39/tc39.github.io/issues/105.

**Comment by codehag** [comment]
Hi @michaelficarra -- thanks for pointing this out, this is a regression
