### ISSUE TITLE
Update screenshot on README

### ISSUE THREAD

**Issue by theNaut1lus** [tc39/tc39.github.io#148]
The screenshot on the readme seems to be getting more and more out of date the screenshot attached as of now in the `README` seems to be very different than the current site version.

So I think we should update the README image with an image of the current version of the website and remove the previous outdated one.

Seems like something that I could work on and submit a PR.

**Comment by rkirsling** [comment]
I think we could just remove the screenshot altogether (along with the word `draft` in the title). :smile:

**Comment by theNaut1lus** [comment]
@rkirsling makes sense since any static screenshot that will be added will eventually become outdated as well
or we could even add an `<iframe>` as well to make things more interesting. (if that's possible)

**Comment by littledan** [comment]
PRs welcome for any of these alternatives.
