### ISSUE TITLE
Prettier not used in pre-commit hook

### ISSUE THREAD

**Issue by Regaddi** [tc39/tc39.github.io#157]
We're using stylelint to lint and autofix staged scss files.
I think we should do the same for javascript files and prettier. Prettier is [already configured](https://github.com/tc39/tc39.github.io/blob/master/.prettierrc) as part of the project.

**Comment by ljharb** [comment]
eesh, i didn’t realize husky was being used. Autoinstalling git hooks is a huge security concern - husky in particular has accidentally installed git hooks in my company’s private internal repo. It’d be ideal to remove it entirely.

**Comment by Regaddi** [comment]
That's a good point. I'd suggest we adjust the CI instead and run the linting on Travis. So anyone working on this site is required to have everything set up locally properly.

**Comment by ljharb** [comment]
yes, that’s the only way to actually ensure consistency anyways, since hooks can be bypassed :-)
