### ISSUE TITLE
Add tc39-notes directory with redirects

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/tc39.github.io#173]
See https://github.com/tc39/Reflector/issues/251.

You could essentially copy all `*.html` files from https://github.com/tc39/notes/tree/gh-pages and add them to a new `tc39-notes` folder on the site hosted here. This would take care of redirecting old notes URLs to the new canonical URLs.

**Comment by allenwb** [comment]
So what's up with fixing this?

The [ecma hosted ECMAScript archive pages](https://www.ecma-international.org/archive/ecmascript/) are publicly visible and known and I just discovered that all of their links to TC39 notes are now broken:

For example: https://tc39.es/tc39-notes/2013-01_toc.html (and others) on https://www.ecma-international.org/archive/ecmascript/2013/index.html  There are dozens of these links on the archive pages and also in my JS History paper that has to go the publishers very soon. 

These all worked when I passed those pages on to Ecma for hosting and I was assured that they would continue to work https://github.com/tc39/Reflector/issues/251#issuecomment-555373517 

We are trying to create a professional quality archive of TC39 documents (not to mention the paper).  It is really unacceptable to break links that have been in public use for such documents.
