### ISSUE TITLE
Copyright Notice Missing From Footer

### ISSUE THREAD

**Issue by Nyameliaaaa** [tc39/tc39.github.io#192]

**Comment by DerekNonGeneric** [comment]
Is anyone aware of what the copyright text should be? Perhaps something along the lines of `TC39 Royalty-Free Task Group` or similar?

**Comment by codehag** [comment]
It might be `© 2020 Ecma International`

cc @ljharb

**Comment by ljharb** [comment]
I'm not particularly sure what's an appropriate copyright here, but that seems fine (although the year is both not required, and can be "just the first year", so it'd be like 1997 or whichever)

**Comment by DerekNonGeneric** [comment]
If the concern is about keeping the year up-to-date, we can use the liquid template engine to handle this. Every time the site is regenerated, the year will be updated so this would be zero-maintenance.

```liquid
{{ "now" | date: "%Y" }}
```

@ljharb, would that be preferable?

**Comment by ljharb** [comment]
No, I'm saying that the copyright never needs to be kept up to date on any site anywhere, that's just needless work that lots of people do :-)

In other words, we should either omit the year, or put the first year Ecma had the copyright, and leave it static.

**Comment by DerekNonGeneric** [comment]
In that case, I wonder if Yulia would mind if I omitted the year since it's not necessary.

**Comment by Nyameliaaaa** [comment]
> I'm not particularly sure what's an appropriate copyright here, but that seems fine (although the year is both not required, and can be "just the first year", so it'd be like 1997 or whichever)

Maybe something like `&copy; Copyright ECMA. All Rights Reserved.`

**Comment by codehag** [comment]
@DerekNonGeneric omitting the year should be fine.
