### ISSUE TITLE
Feature request for https://tc39.es - email list newsletter

### ISSUE THREAD

**Issue by trevordmiller** [tc39/tc39.github.io#194]
It would be helpful to have a way to subscribe to official TC39 updates via an email list newsletter. Currently the only way I'm aware of updates is via newsletters like JavaScript Weekly, but I would like to follow the official source directly for updates (especially stage 3 => stage 4 proposals that I can start using once they become stable).

Thank you for all you do!

**Comment by ljharb** [comment]
You can reference https://github.com/tc39/proposals for the current stages; generally stage 3 is when things are considered “stable” by the ecosystem (it’s also when engines are encouraged to ship).

For such a newsletter to exist, someone would have to volunteer to write it :-)

**Comment by trevordmiller** [comment]
By "newsletter" I mean an email list that sends out automatic updates so that manually checking the site / repo isn't necessary for those who want to stay up-to-date (not a manually written thing). But perhaps this is specific to me, I'll close the issue for now. Feel free to re-open if others seem to want this as well. Thanks!
