### ISSUE TITLE
Simplify Arrow Syntax

### ISSUE THREAD

**Issue by johnaweiss** [tc39/tc39.github.io#196]
If the whole point of arrow syntax is to simplify, then it's too complicated. 

- The parameter list for a function with no parameters should NOT be written. 
- Eliminate the `=` 

Instead of this:

var f = () => ...

it should be:
var f => ...

**Comment by ljharb** [comment]
If this is meant as a feature request, this repo (the website) isn't the place to post it - see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for that.
