### ISSUE TITLE
Give Non-1 Iterators the Same Pre/Post Behavior as Value-1 Iterators

### ISSUE THREAD

**Issue by johnaweiss** [tc39/tc39.github.io#197]
This seems to be a language inconsistency. 

Currently spec:
```
let a = 5
let b = a++
b == 5

let a = 5
let b = ++a
b == 6  
```

This is a useful behavior. Why should only value-1 iterators enjoy it? 

Here is a possible syntax for non-1 iterators. This syntax seems maybe good, because it's not an existing syntax. Currently, it would raise an error, so adding it to the language won't break anything. Also seems good because it's the same operator (++) as the value-1 pre/post operator. 

```
// Pre: 
5 ++a,  or ++a 5

// Post: 
a++ 5
```

The following form shouldn't be used, because it's already in-use, and it's current behavior is (non-intuitively) prefix. Therefor, changing it to postfix would break existing code. 
`a += 5`

**Comment by ljharb** [comment]
If this is meant as a feature request, this repo (the website) isn't the place to post it - see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for that.

Remember, though, that both of these are already valid syntax:
```js
5
++a

;

a++
5
```

**Comment by johnaweiss** [comment]
Thx, i registered over there. Waiting to get approved. 
Thx for your comment about syntax, i'm sure there's a solution. Maybe remove the space:

5++a
a++5


On 5/7/2020 8:04:44 PM, Jordan Harband <notifications@github.com> wrote:
If this is meant as a feature request, this repo (the website) isn't the place to post it - see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal [https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal] for that.
Remember, though, that both of these are already valid syntax:
5 ++a ; a++ 5
