### ISSUE TITLE
Keeping the website up-to-date

### ISSUE THREAD

**Issue by DerekNonGeneric** [tc39/tc39.github.io#199]
Yulia had mentioned that she would like some help keeping the website up to date. Is there anything that needs to be prioritized? Please let me know how I can be of assistance. :)

/cc @codehag

**Comment by codehag** [comment]
Hi Derek, anything specifically interesting for you?

It is an information website. At some point i would like to automatically generate information on it (doing it manually as I haven't found the time), and there are a number of smaller bugs as well.

**Comment by DerekNonGeneric** [comment]
After taking a look at the issues currently open, I think I would be most interested in helping out with contributing a proper footer. There are a couple of open issues specifying its contents.

- https://github.com/tc39/tc39.github.io/issues/5
- https://github.com/tc39/tc39.github.io/issues/192

Although I do wonder if my efforts towards this would go unappreciated seeing as how there would be a banner covering it.

![image](https://user-images.githubusercontent.com/17770407/87381791-7eeb3780-c563-11ea-9cac-73366fbe6a86.png)

There might be a more clever way of alerting users to being interested in feedback while not covering the footer. Is anyone currently working on this? I can probably take care of those two open issues tomorrow.

**Comment by DerekNonGeneric** [comment]
> It is an information website.

I used to have a website like this. To accomplish the automation you're probably interested in, I was scraping and parsing HTML from various pages online. It all went into a nice and neat table at the end. Unless there is some information system that contains all of the information about the various proposals, it seems like a similar approach would need to be taken here.

Although I'm not too familiar with the way TC39 works, it seems like the source of truth for the stages of these proposals is the [tc39/proposals](https://github.com/tc39/proposals) repo.

If so, and unless the main page is only supposed to contain stage 3 proposals, perhaps the various tables of the Markdown files in the [tc39/proposals](https://github.com/tc39/proposals) repo can be parsed for the data necessary to populate the [tc39.github.io/_data/](https://github.com/tc39/tc39.github.io/tree/master/_data) directory with files for each stage.  It seems like they can use the same data structure already being used for [stage3.yml](https://github.com/tc39/tc39.github.io/blob/master/_data/stage3.yml).

After the footer is done, I think I can take care of the following two issues.

- https://github.com/tc39/tc39.github.io/issues/30
- https://github.com/tc39/tc39.github.io/issues/59

These issues are a bit more involved. Fortunately, I have solved this problem for myself in the past and wouldn't mind contributing a solution to this as well. With no real information system in place, it seems like some data (i.e., examples) would need to be collected from the proposal repos themselves. I will have to look further into that problem once I get there and will keep you posted.

**Comment by codehag** [comment]
Sure, we can add the copyright at the bottom. #30 and #59 are indeed the issues I was thinking of. That is probably the most important thing wrt keeping this up to date.

Another good starting issues is #147, which would improve accessiblity.

**Comment by DerekNonGeneric** [comment]
> [&hellip;] unless the main page is only supposed to contain stage 3 proposals [&hellip;]

There appears to be no desire to have `stage0.yml`, `stage1.yml`, `stage2.yml` data structures in [`_config`](https://github.com/tc39/tc39.github.io/blob/master/_data/) since they aren't featured on the site. (Whether or not this is by design is still unclear to me.) I imagine stage 1 and stage 2 proposals would be good candidates to be featured on the site though. Would this be part of keeping the website up-to-date? If it's going to all be automated, I don't see any drawbacks in doing so since it would be zero maintenance burden. I must admit, I am a bit unclear on what all needs to be synchronized with GitHub.

**Comment by codehag** [comment]
they are not part of the site by design. In the past, people have gotten very upset about stage 1 proposal, without realizing what stage 1 signifies. Stage 3 is the stage at which software developers can start trying things.

Only stage 3 needs to be synchronized.

**Comment by DerekNonGeneric** [comment]
> Only stage 3 needs to be synchronized.

Alrighty. I think you can ignore my intention of putting all stages into data structures as they won't be rendered on the site. (For some reason, the GitHub UI is preventing me from replying directly to your question in the open PR, so I'll just mark it as resolved.)

**Comment by septs** [comment]
https://github.com/JSCIG/dataset/blob/gh-pages/proposals.json

**Comment by smorimoto** [comment]
I think this was fixed in #290, right?

**Comment by jasonwilliams** [comment]
Yes I think so, this can probably be closed in favour of that
