### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by codehag** [tc39/tc39.github.io#218]
Hey folks,

We have been running the website for about a year, and I think we are getting to the point where we should open it up, and make it more accessible internationally. That means localization. This issue will be used to track and plan that work.

**Comment by codehag** [comment]
Some people I want to get into the conversation to get it started are @chicoxyzzy @septs @hemanth and @xtuc -- any ideas here?

The first one I am thinking of, is there is the fantastic work done by JSCIG. If they are willing, I would love to work together and possibly share translations?

**Comment by littledan** [comment]
cc @pusongyang

**Comment by littledan** [comment]
I also want to suggest that we localize the TC39 Discourse, to allow discussions in non-English languages for early proposal design, to make things more comfortable initially.

**Comment by hemanth** [comment]
Sure @codehag count me in!

**Comment by septs** [comment]
https://developers.google.com/search/docs/advanced/crawling/managing-multi-regional-sites?hl=en

**Comment by septs** [comment]
> The first one I am thinking of, is there is the fantastic work done by JSCIG. If they are willing, I would love to work together and possibly share translations?

Yep

**Comment by codehag** [comment]
thanks @septs! for the pointer.

Reading it, there is a distinction between language and region. Due to this being a volunteer effort, for now, I guess we will approach this with what languages we have available to us. This will unfortunately self select to current tc39 delegates, but hopefully it will encourage others to do localizations.

I can probably cover german and some russian (but I will need help). We have a strong representation of chinese speaking delegates. Do we have other languages we can cover in an MVP?

Based on those languages (I will use german as an example here), we can either do a subdomain `de.tc39.es` or a directory `tc39.es/de` (I don't have strong opinions, one or the either is fine). To complement that, we should have a clearly visible drop down for changing the language. I don't think that we need to automatically detect where the visitor is coming from (and this will be complicated with European law) but that can be a stretch goal. For this drop down, we will need a design.

With language selection in place, we can then leverage the existing infrastructure on jekyll. The goal is to keep this change as light weight for now as possible.

With this in place, the next question is data structure. I propose that we update our data ymls (https://github.com/tc39/tc39.github.io/tree/master/_data) to have the language in the name, ie stage3.de.yml, and keep localizations separate this way. Would that be reasonable? I suppose, if we are missing a language we can fall back on english?

**Comment by chicoxyzzy** [comment]
I'm willing to help with Russian localization of website and docs (I think that we should translate "TC39 process", "How we work", and maybe something else) and help supporting Russian-speaking Discourse too if we'll have it eventually 👍.

We may want to use a [Unicode BCP 47 locale](https://www.unicode.org/reports/tr35/tr35.html#Canonical_Unicode_Locale_Identifiers) identifier, i.e. `de-DE` instead of `de`

**Comment by septs** [comment]
> For this drop down, we will need a design.

I think we need user experience designers.

**Comment by xtuc** [comment]
I don't know how easy it would be to make subdomains work with GitHub pages. Directories seem easier to implement.

Documents like "TC39 process", "How we work", etc doesn't seem to change too much. On the other hand proposal's content could change relatively often, especially in the early stages. If the data is crawled/imported automatically i'm concerned that translation will become out of sync. Which is probably less helpful than the original english version.

**Comment by chicoxyzzy** [comment]
What do people here think will be the best approach for multi-lingual forums: should they be subforms of es.discourse.group or a separate instances?

I've just started to work on translation of the Code of Conduct to Russian and I think that it could be a good starting point for any localization =)

UPD: CoC translation is almost done in https://github.com/chicoxyzzy/code-of-conduct/pull/1. There are a few complicated parts I need help with,

**Comment by ljharb** [comment]
The main concern i have is that translations stay up to date - what are the plans to ensure that’s the case?

**Comment by chicoxyzzy** [comment]
For documents on GitHub there definitely should be some automation. When original document file is changed, a new issue should be created for translated documents.

**Comment by codehag** [comment]
I think as @chicoxyzzy suggests, we can have an action to signal that a translation needs updating.

However, the biggest churn will be proposals. Since we are only interested in stage 3 proposals, and only their descriptions and titles, I don't expect much change after a translation is made.

**Comment by septs** [comment]
@codehag I think the only needs to translate the proposal title (make readers interested)

**Comment by DerekNonGeneric** [comment]
> [&hellip;] only needs to translate the proposal title (make readers interested)

Regarding the proposal data, I just took a look at the current values for the titles in [`stage3.yml`](https://github.com/tc39/tc39.github.io/blob/master/_data/stage3.yml) and noticed that many of the proposal titles are code literals. For this website, it seems like the descriptions would actually be of most value to translate (make readers interested). Descriptions seem to be rather short (a sentence or two) and I've started to notice a pattern between them, so once we can get the commons words (phrases) localized, it shouldn't be too difficult to keep them updated in the future.

**Comment by chicoxyzzy** [comment]
BTW for the website we probably can try to get people involved by adding "Translation is not complete. Help translate it (link to localization file)" if we fallback to English. Also we can create automation: when new PR is created, add certain reviewers for every language.

**Comment by DerekNonGeneric** [comment]
I have a collaborative document where can suggest translations for the veneer of the site (buttons and things), plus an example of the proposal description pattern I was talking about. I've mostly taken care of the Spanish one so far (Google translate was very wrong about a few of these 😂) and started the Chinese one (probably wrong). This document is inspired by [Chinese translations for Git package](https://github.com/git/git/blob/master/po/zh_CN.po) since we will likely be using the same software and they have good translations already. Feel free to pitch in, I may eventually be able to get the French and Portuguese ones done (since there aren't many words), but don't want to over-promise.

🔗 https://docs.google.com/document/d/1ZgD5EPVIU2hfQEuX3xjxEwtB06SabHcPSfv0SYEtWsk/edit?usp=sharing

**Comment by septs** [comment]
https://weblate.org

**Comment by codehag** [comment]
Weblate looks like a great tool, but we would need to find funding for it, as the free tier would require hosting anyways. For now let's create a minimal version of this and work out whatever issues we find. I am leaning towards what @DerekNonGeneric has started and just turning that into files.

Also, I suspect that automatic translation will be something we need to rely on a bit here. As @septs mentioned, the name is likely the most important part. The description may also help, and is also short. I have found deepl.com to be pretty accurate for translation (it is trained on legal proceedings). While this won't work for larger documents (such as what @chicoxyzzy is translating, the process document and how we work repo) it should work for short text and be easy to verify. But it has limited language support. What I can do is run all of the languages through deepl and get a base line set up...

**Comment by codehag** [comment]
Also, following the suggestion from @xtuc, we will do this as directories rather than subdomains.

**Comment by septs** [comment]
> Also, following the suggestion from @xtuc, we will do this as directories rather than subdomains.

Edge case:
https://github.com/tc39/tc39.github.io/tree/master/de-DE
https://github.com/tc39/de-DE (such repo is not allowed?)

https://tc39.es/de-DE (it expected repo is ?)

**Comment by septs** [comment]
> cover all proposals

use https://weblate.org or other platform?

**Comment by codehag** [comment]
I suppose you mean, crowd source translations via weblate? I don't have any concerns about weblate itself, and we can use a compatible data format like dtd. The issue there is not one of technology, but of getting enough volunteers to keep things up to date. Weblate itself relies on this and so far only has partial translation. Even with MDN, we were unable to consistently get translations for all features without hiring people to do that job. (though it would be amazing if we could have mdn fully localized... it looks like this right now: https://developer.mozilla.org/zh-CN/docs/Mozilla/Projects/SpiderMonkey/Build_Documentation for example)

I think this problem won't be easily solved unless we have a dedicated team for it. Establishing that will take some time and might fail due to lack of funding. Weblate itself has a requirement that we either pay for the service, or pay for hosting. At the moment the tc39 website is cost free for tc39 and ecma. This doesn't mean that won't change -- We can get money for it, but I would like to work on a more comprehensive funding structure before we do that. 

Unless I am missing something here, which I might be...

**Comment by littledan** [comment]
I want to suggest that we simply present the English descriptions on the otherwise non-English websites when no one has yet volunteered to translate them. We can make a big "edit" link to help people create a PR to contribute the translation. So we can translate the static content once, into various languages, so at least people can get a broader introduction without having to understand English--hopefully this is lower overhead.

**Comment by codehag** [comment]
Ok, how about this as the plan with subtasks:

* [x] add internationalization for jekyll
  * [x] for example https://github.com/vwochnik/jekyll-language-plugin. We can use yaml for the language specific parts: https://github.com/vwochnik/jekyll-language-plugin/wiki/YAML-front-matter
  * [x]  Move english text into a dedicated yaml file for the main page. We can also break these up into smaller sub sections, i have no strong opinion on how this is done, but treating english as one translation will be a good way to prove this out.
  * [x] set the english translation as the fall back translation for any untranslated content. This includes links
* [ ]  Translate core documents into selected languages [de, ru, en, cn]
  * [ ] [Process document](https://tc39.es/process-document/) -- probably delay this as there will be a couple more changes over the next months
  * [ ] [Code of Conduct](https://tc39.es/code-of-conduct/)
  * [ ] Jory's "how to participate" document or Allen's ["patterns for participation"](http://wirfs-brock.com/allen/files/papers/standpats-asianplop2016.pdf) 
  * [ ] [agenda topic rules](https://github.com/tc39/agendas/blob/master/template.md#agenda-topic-rules) (to be linked from the agenda, as this doesn't change much)
  * [ ] README of [How-We-Work](https://github.com/tc39/how-we-work/), with a prioritization of which documents need translations. I would propose that "how to champion", "how to give helpful feedback", and "how to write an explainer" be the first ones. Last one will be terminology as that one changes the most.
* [x] Machine translations of descriptions and titles for all stage 3 proposals
* [ ] Design a way to switch between languages

**Comment by chicoxyzzy** [comment]
Machine translation may work not so good for some languages. For example, it's common to leave keywords as is and not translate them, cause that what people use in the code. I think that it's better to leave titles in English than apply machine translation or have both English and machine translation.

**Comment by DerekNonGeneric** [comment]
- [x] add internationalization for jekyll 
  - [x] here are [all of the gems available in the GitHub Pages gem bundle](https://pages.github.com/versions/), but YAML frontmatter for localization 👍 
  - [x] Move English text into a dedicated YAML file for the main page. (Localization dropdown links English to `/en/`)
- [ ] Machine translations of descriptions and titles for all stage 3 proposals 💭 (seems perfectly reasonable)

**Comment by codehag** [comment]
@chicoxyzzy i have a similar concern. I just did a first pass and reserved a few words in it. Happy to go through it again -- for now it is just a starting point. 

For now, we have the translation plugin in place, and all localizable strings have been localized. It might be better organized.

**Comment by codehag** [comment]
Some uncovered issues so far:
1) Shared data, such as code examples and dates, don't need to be duplicated across translations. 
1a) Dates should be in a format that can be automatically localized, rather than requiring translations.
2) the font looks strange in Chinese, or is it just me?

<img width="215" alt="Screenshot 2020-12-02 at 10 34 51" src="https://user-images.githubusercontent.com/26968615/100855039-06d9cb80-348a-11eb-915e-676e48c7ca44.png">

@septs @Jack-Works is it normal for the first character to be bold? I am not familiar enough to know...

3) In some cases, we may rely on machine translation, as I imagine that we won't be able to keep a very close eye on this. In this case, I suggest that we use an api such as deepl to do automatic translation, and have a disclaimer on the site notifying users that the site is partially machine translated, and that contributions are welcome. I've seen similar disclaimers in European sites -- what do people think?

**Comment by Jack-Works** [comment]
@codehag I guess because some necessary fonts are missing on your computer, some strange CSS rules applied, or some of characters are parsed as Japanese Kanji (so they're using a different font)

**Comment by codehag** [comment]
thanks @Jack-Works  -- if it looks ok to you, we can leave it as is. otherwise I am happy to find another font.

@chicoxyzzy you mentioned a while ago:
> We may want to use a Unicode BCP 47 locale identifier, i.e. de-DE instead of de

I don't think we want to do localizations for, for example, de-AT and de-DE, but having de-De and not de-AT might send the wrong signal. Also, it looks like just `de` is valid per BCP 47?. At the same time, the character set used in simplified and traditional Chinese is different.. in which case zh-Hant and zh-Hans might really make sense as per https://tools.ietf.org/html/bcp47#appendix-A. But these are also a bit esoteric to write in the url bar, and would only really work if we have a link/language menu or language detection. I am not too sure what to do here as a minimal solution. Any thoughts?

**Comment by codehag** [comment]
I spoke with @zoepage (who did the information architecture and design of the site in the beginning) about taking a look at the button for switching languages. She said she might have time during the winter break. I will break that out into it's own bug, cc'ing her here for the context and to inform others of what will happen in terms of design.

**Comment by codehag** [comment]
Closing this in favor of smaller bugs. Please open any localization issues as they are found.

**Comment by chicoxyzzy** [comment]
Should we create a separate issue for multi-lingual Discourse?

**Comment by codehag** [comment]
Yes please

**Comment by codehag** [comment]
Though, possibly that should be done via discourse?

**Comment by chicoxyzzy** [comment]
There is a [topic](https://es.discourse.group/t/multi-lingual-discussion-on-discourse/553) on discourse, but posting there is limited to delegates group.
