### ISSUE TITLE
Structured pages (SEO)

### ISSUE THREAD

**Issue by septs** [tc39/tc39.github.io#221]
> Google Search works hard to understand the content of a page. You can help us by providing explicit clues about the meaning of a page to Google by including structured data on the page. Structured data is a standardized format for providing information about a page and classifying the page content; for example, on a recipe page, what are the ingredients, the cooking time and temperature, the calories, and so on.

from https://developers.google.com/search/docs/guides/intro-structured-data

Use JSON-LD structured page for Google Search results?

Reference:
- https://schema.org/WebPage
- https://schema.org/ItemPage
- https://schema.org/Event
- more, see https://schema.org/docs/schemas.html

**Comment by septs** [comment]
CC @codehag

**Comment by codehag** [comment]
This sounds like a great idea. I don't have much experience in this area so I am happy to let you take the lead on this. Do you need any information or access to do that?

**Comment by codehag** [comment]
We can likely have this localized as well
