### ISSUE TITLE
[Bug] The page is empty

### ISSUE THREAD

**Issue by Jack-Works** [tc39/tc39.github.io#223]
![image](https://user-images.githubusercontent.com/5390719/100956016-93e85780-3552-11eb-9626-fb584e404259.png)

**Comment by codehag** [comment]
ah, that is unexpected.

**Comment by codehag** [comment]
Temporary fix is online, full fix is incoming.

**Comment by codehag** [comment]
We are back up and running:

tc39.es
tc39.es/de/
tc39.es/ru/
tc39.es/zh-Hans/

We need a redirect for zh-Hans to zh-Hans/ -- the other locals do this automatically but not this one.
