### ISSUE TITLE
Localization proof-read of German

### ISSUE THREAD

**Issue by codehag** [tc39/tc39.github.io#227]
The only language that doesn't have a native speaker to proof read it is German. I can read German, and understand it mostly, but I can't tell if something is "not normal". Any help in this direction is very much appreciated!

**Comment by Regaddi** [comment]
I'm glad to help ✋

**Comment by codehag** [comment]
@Regaddi thank you!!!!

**Comment by codehag** [comment]
@Regaddi you can find it here: https://github.com/tc39/tc39.github.io/tree/master/_data/de and here: https://tc39.es/de/

**Comment by Regaddi** [comment]
I'll prepare a PR with suggested changes for easier discussion. Should have it ready tomorrow :+1:

**Comment by codehag** [comment]
fixed by #229
