### ISSUE TITLE
Some of the content is 404

### ISSUE THREAD

**Issue by smorimoto** [tc39/tc39.github.io#238]
| Page rating (desc) | URL                                                                       | Organic traffic | HTTP status code | Content type             | Depth | No. of inlinks |
| ------------------ | ------------------------------------------------------------------------- | --------------- | ---------------- | ------------------------ | ----- | -------------- |
| 44                 | https://tc39.es/import-assertions                                         | 0               | 404              | text/html; charset=utf-8 | 1     | 1              |
| 44                 | https://tc39.es/at                                                        | 0               | 404              | text/html; charset=utf-8 | 1     | 1              |
| 44                 | https://tc39.es/proposal-top-level-await/img/module-graph-simple.svg      | 0               | 404              | text/html; charset=utf-8 | 3     | 0              |
| 44                 | https://tc39.es/proposal-top-level-await/img/module-graph-missing.svg     | 0               | 404              | text/html; charset=utf-8 | 3     | 0              |
| 44                 | https://tc39.es/proposal-top-level-await/img/module-graph-cycle.svg       | 0               | 404              | text/html; charset=utf-8 | 3     | 0              |
| 44                 | https://tc39.es/proposal-top-level-await/img/module-graph-cycle-async.svg | 0               | 404              | text/html; charset=utf-8 | 3     | 0              |

###### This list is based on the results of using Ahrefs' site audit tool.

**Comment by DerekNonGeneric** [comment]
The first two will be fixed by https://github.com/tc39/tc39.github.io/pull/236.
