### ISSUE TITLE
long form sections

### ISSUE THREAD

**Issue by codehag** [tc39/tc39.github.io#26]
In the designs we have a long form about section and specs section.  I started thinking about what kind of information could be added there and there is some good stuff we could summarize. What would be great is to have feedback on what we need.

Here my notes on the two sections in question: 

Information that can be added to the long form of the about:

- taking care of ECMA-262, ECMA-402, ECMA-404, ECMA-415
- summary of organizations that take part, (commercial, ngos, etc)
- invited experts
- the many contributors who comment, improve, and give feed back on proposals

Information that can be added about the specs:

- the proposal process
- short summaries about each stage. 
- which stages are safe to use
- where the specs are hosted, and how the specs are integrated
- what the conventions of the spec are, and how to read proposal spec edits (probably as a link out?)

@zoepage @littledan thoughts?

**Comment by codehag** [comment]
If we do have them, I'd like to start iterating on the text today, so let me know!

**Comment by codehag** [comment]
Information that can be added to the long form of the about:

- taking care of ECMA-262, ECMA-402, ECMA-404, ECMA-415
- summary of organizations that take part, (commercial, ngos, etc)
- invited experts
- the many contributors who comment, improve, and give feed back on proposals
-

**Comment by codehag** [comment]
closed by accident!

**Comment by zoepage** [comment]
Thanks for the write up! Looks great!
Would the `spec` section include community or would this be a separated topic?

> the many contributors who comment, improve, and give feed back on proposals

Does this mean listing them or explaining their work or both?

> Information that can be added about the specs:

What do you think about adding something about the spec tests? Maybe also how to write them etc?

**Comment by littledan** [comment]
Let's continue developing this content in the TC39-internal how-we-work repository. Some of this is pretty subtle.

**Comment by codehag** [comment]
@zoepage we wouldnt add "how to" information here because it is really detailed. This would be a general overview.

**Comment by codehag** [comment]
This has been resolved
