### ISSUE TITLE
replace vnu-jar with html-validate

### ISSUE THREAD

**Issue by ryzokuken** [tc39/tc39.github.io#265]
https://www.npmjs.com/package/html-validate is a Node-based alternative to the vnu-jar HTML validator. The current setup requires setting up Java on a system, which is very unintuitive for contributors and is probably also slowing CI builds down.

This would simplify the build process, which would make it easier to contribute and move towards eventually simplifying the setup so we could remove Docker and GNU Make.

Moves us closer to #264.

**Comment by osBins** [comment]
Hey, I would like to work on this issue!

**Comment by ryzokuken** [comment]
Perfect, @osBins! Please feel free to ask here or ping me directly if you need any help. Happy hacking!

**Comment by osBins** [comment]
@ryzokuken running `npm i` updates the package-lock.json (changes lockfileVersion from '1' to '2', among other additions). Is there a way to retain package-lock.json or would it be fine to commit the updated change?

**Comment by ryzokuken** [comment]
Yeah, looks like the package-lock.json file was generated using an old version of npm. Feel free to commit.
