### ISSUE TITLE
Migrate from Travis to Github Actions

### ISSUE THREAD

**Issue by jasonwilliams** [tc39/tc39.github.io#267]
Github Actions has much better transparency (just click Actions at the top), so would be much better for contributors of this project. 

The aim would be to transform this config https://github.com/tc39/tc39.github.io/blob/master/.travis.yml into a `.github/workflows/release` action

It might be worth doing this after migrating from Ruby, so there's only Node to setup.

- https://github.com/actions/setup-node#usage

Related to: https://github.com/tc39/tc39.github.io/issues/264

**Comment by codehag** [comment]
Very strong support for this!

**Comment by ryzokuken** [comment]
Strong support from me as well, who has admin access to Travis for this repo btw? Or does it allow all GH admins to manage it?

**Comment by codehag** [comment]
I do, I will check with you both if you can access it.
