### ISSUE TITLE
What is the purpose of Class, it seems to do nothing but make junk.

### ISSUE THREAD

**Issue by andrewhodel** [tc39/tc39.github.io#276]
You need a variable to store the class in anyway.

Is the desire for the continuation of creating junk because porting was easier?  Many existing ports from other languages used a class structure, etc...

```
// nodejs example
// it creates what you would call classes
//
// or you can use exports only

exports.init = function() {

	var o = {data_to_keep: 'asdf'};

	// return the object
	return o;

}

module.exports = class Junk {

	// this is so you can remember every language's super cool module system

	// see how powerful it is, you store an object automatically with all these extra
	// "how to module" requirements in your code
	// and you get to deal with functions and bind overwriting the this object that is the class!

	// this is ran when the class is "instantiated" is the word used now
	constructor() {

		this.data_to_keep = 'asdf';

	}

}
```

Class is terrible when dealing with callbacks and bind, and the truth is that directional assignment operators should exist to work with bind because of how pointers and references ruin a person's and especially a team's ability to have a conversation about their work without over-ruling junk.

**Comment by andrewhodel** [comment]
`will write a js compiler with callbacks as threads...`

**Comment by andrewhodel** [comment]
I know this is for your website, but you are a bit confused about website developer.

<img width="364" alt="Screen Shot 2022-03-27 at 6 19 04 PM" src="https://user-images.githubusercontent.com/741705/160273125-2acbd27a-01f3-410d-8d6c-3e9e5a470ada.png">

How do I contact the writers, not the teams using it to pad rooms?

**Comment by ljharb** [comment]
This kind of discussion is definitely not appropriate here, and is barely going to be productive on https://es.discourse.group

Please familiarize yourself with our code of conduct before posting further.

**Comment by andrewhodel** [comment]
I assume by conduct you don't mean other people following my work?

**Comment by ljharb** [comment]
No, i mean our rules for behavior.
