### ISSUE TITLE
Can't find old revisions of ECMA-262

### ISSUE THREAD

**Issue by dotproto** [tc39/tc39.github.io#285]
I just came across tc39.es while trying to find previous versions of the ECMAScript specification. Having used the [Ecma International](https://www.ecma-international.org/publications-and-standards/standards/ecma-262/) version of the ECMA-262 page a number of times, I expected to find archives similar to what that page provides. Given this expectation, I found a few aspects of the current site confusing.

* The `Specs` option in the navbar does not have an "previous versions", "old revisions", or "archives" entry
* `Specs` > `ECMA-262, ECMAScript` links to the current draft specification, not the latest version published as ECMA-262
  * I would expect this entry to be labeled something like "ECMA-262, ECMAScript (Nightly draft)"
* The paragraph under the "Specs" header makes no mention of the current or archived versions of ECMA-262.
* The only reference to "archive" on the page appears in the footer and links to https://tc39.es/archives/ which is a completely different kind of archive.

In order to help people looking for similar information, I'd like to suggest a couple of potential changes

- [ ] Create a new page at `tc39.es/revisions` that lists and links to all previous revisions of the specification. Each entry in this list should link to the HTML and PDF versions as appropriate.
- [ ] Add a "Previous versions of ECMA-262" link to the bottom of the `Specs` nav menu that links to `tc39.es/revisions`
- [ ] Rename the "Specs" section of the index page to "Process" to better reflect it's content.

**Comment by DerekNonGeneric** [comment]
> The only reference to "archive" on the page appears in the footer and links to https://tc39.es/archives/ which is a completely different kind of archive.

You are right about it being a completely different kind of archive. Sorry for not setting up expectations there. At the time, I was not sure about the story behind that page when I added a link to it there.

At the time, I had only been involved in a completely different archive as well ([`doc/archive` in `nodejs/modules`](https://github.com/nodejs/modules/tree/main/doc/archive)) and was unsure as to whether that page was intended to be public-facing or not, but having already been indexed by Google and appearing in search results, it seemed like a good idea to put a link to it there.

I'm not an app developer, but was told that this project had been intended to be perceived as being single-page app-like, so more pages being added here may not be planned. Lately, it seems like there has been renewed interest in "archive", though. Perhaps this issue would be more appropriate for [`tc39/archives`](https://github.com/tc39/archives) and be well-received there?

**Comment by ljharb** [comment]
The spec is a living standard; old versions are all obsolete. Previous years are present, though - but it’s not recommended to use them.

**Comment by dotproto** [comment]
Thanks for the correction, @ljharb. This was the first time I've seen the spec described as a living standard. I realize now that the "About this Specification" section clearly states that "[the] document at https://tc39.es/ecma262/ is the most accurate up-to-date ECMAScript specification." It looks like this text was added ~3 years ago, so it seems my mental model was just out of date.

@DerekNonGeneric, I don't have strong feelings about where old versions of the spec are hosted, but I do think it would be useful to include links to the appropriate page in the nav and possibly in the page body.

I'm a JavaScript developer; the longer I work on the web, the more value I've found in directly consulting  relevant specifications and their historical versions. Since https://tc39.es/ecma262/ appears to be the canonical home for the current version of the spec, I think it makes sense that the landing page for that domain would direct reads to TC-39 and ECMA-262 related resources. 

If the site maintainers are disinclined to host the previous versions of the specification on this site, could we simply link to https://www.ecma-international.org/publications-and-standards/standards/ecma-262/?

**Comment by DerekNonGeneric** [comment]
Even though ECMA-262 is a living standard by definition, unlike the WHATWG living standards, TC39 seems to put some effort into publishing annual stable snapshots of the specification. I am unsure why this project does not currently acknowledge that effort, but I don't see why visitors to this page should be left in the dark about it. If there seems to be agreement that it should appear here, I am unsure how best to surface it.

I wonder what @smorimoto and the other currently-active maintainers of this project think.

**Comment by ljharb** [comment]
Visitors to this page won't likely benefit much from it, since virtually no implementation fully and solely implements any given edition year - in my experience, every implementation has a mishmash of ES(N) and ES(N + M) features and stage 3+ proposal features.
