### ISSUE TITLE
Should mention JavaScript

### ISSUE THREAD

**Issue by domenic** [tc39/tc39.github.io#29]
I think one of the most confusing things for newbies is the JavaScript/ECMAScript distinction. I would suggest explaining it.

This could be done with one of two approaches:

1. Use JavaScript throughout the site, and have an appendix or FAQ or similar explaining ECMAScript
2. Use ECMAScript throughout the site, and have an appendix or FAQ or similar explaining the connection to JavaScript

I think (1) is more friendly toward web developers. (2) would, IMO, require some extra work to quickly clear up the confusion. For example the large homepage text saying "Specifying ECMAScript" that was shown on the slides should be something like `Specifying ECMAScript <small><a href="...">What is ECMAScript and how does it relate to JavaScript?</a></small>`

**Comment by codehag** [comment]
I believe this is addressed, at least for the current content.
