### ISSUE TITLE
Populate proposal data from tc39/dataset

### ISSUE THREAD

**Issue by jasonwilliams** [tc39/tc39.github.io#290]
Populate the website with data from https://github.com/tc39/dataset

Eleventy Fetch seems useful (and for local development):
https://www.11ty.dev/docs/quicktips/cache-api-requests/

**Task:**
A new JS file would need to be added to https://github.com/tc39/tc39.github.io/tree/master/_data which has a similar format to the link above. It fetches proposal data and returns a format we're expecting. At build time this API would be fetched and the data can be iterated through in the template.

**Triggering Action from dataset**
Either https://github.community/t/triggering-by-other-repository/16163/2 or a cron action to rebuild the website at a set interval

**Issues:**
- Translations? I'm not sure we would have a solution for this if pulling from the API. I'm open to any ideas

**Related:**
- https://github.com/tc39/tc39.github.io/issues/199
- https://github.com/tc39/tc39.github.io/issues/60

**Comment by codehag** [comment]
Translations should maybe be pushed to the dataset.
