### ISSUE TITLE
Scraping data using nightly hooks while keeping GitHub Pages

### ISSUE THREAD

**Issue by keithamus** [tc39/tc39.github.io#30]
After discussing with @codehag about some requirements around scraping data for use with the website, I thought I'd demonstrate a working example of this with Jekyll + GitHub pages:

The documentation site (http://www.chaijs.com/) for the Chai testing library currently uses Jekyll. We have a few parts of the site that are automatically updated - for example http://www.chaijs.com/plugins/ is a list of community maintained plugins, which gets updated every day using a nightly build on Travis-CI. Additionally http://www.chaijs.com/releases/ is automatically generated nightly.

Travis has the capability to run schedule builds (the "Cron Jobs" section of settings offers this) and so `chais/chaijs.github.io` on Travis is configured to run every 24 hours, provided there hasn't already been a commit to master in the last 24 hours.
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/118266/40375267-29011ac4-5db9-11e8-8587-87013c9f5399.png">

This means that the CI build job is run at a minimum interval of 24 hours. Part of that build script is generating plugin data:

https://github.com/chaijs/chaijs.github.io/blob/24af0083ee0ec7bafe117fec4e9c09dd4e567575/Makefile#L41-L46

Then there is some makefile hackery to say if the Make task is being run on Travis, on the master branch, build the site and if the working directory is unclean, then commit the new changes to master.

https://github.com/chaijs/chaijs.github.io/blob/master/Makefile#L93-L115

Hopefully this provides a good example of how Jekyll sites can have some "dynamic" data (for certain values of "dynamic").

**Comment by jasonwilliams** [comment]
This is a fantastic insight, thanks @keithamus

**Comment by jasonwilliams** [comment]
I think this can be closed now as our stack has changed quite a bit since this was raised
