### ISSUE TITLE
Modal inviting comments / contributions

### ISSUE THREAD

**Issue by codehag** [tc39/tc39.github.io#31]
someone recommended that we include a modal or some form of info box that invites people to make comments / suggestions on how the website works. I think this is a great idea. We can include a link to this repo and a short message. thoughts?

**Comment by ljharb** [comment]
Could it point to github issues, rather than adding a separate moderateable space?

**Comment by codehag** [comment]
yes! this is a good suggestion, lets do that!

**Comment by xtuc** [comment]
We talk about that during the meeting.

I would suggest to add a message like: "this is a beta, click here to send feedback" in the header.
