### ISSUE TITLE
feat(infra): Consider using an framework (nextjs).

### ISSUE THREAD

**Issue by AugustinMauroy** [tc39/tc39.github.io#316]
I propose to use a javascript framework.

I suggest to use [Nextjs](https://nextjs.org). Because :
* We can deploy with Github Page
* It uses react
* We can use typescript for security.
* We can make unit test on the component
* We can do I18n

A big argument is that it is a javascript framework. Knowing that our community is around javascript it will be easy for everyone to contribute

> I am aware that an issue on this subject has already been made. But I think we should reconsider a new infra.

**Comment by smorimoto** [comment]
> A big argument is that it is a javascript framework.

We wanted to avoid favouritism of js frameworks, as an endorsement could negatively affect people.

> Knowing that our community is around javascript it will be easy for everyone to contribute

We also do not consider it a barrier to entry, and we are worried about moving to a js framework as it may show favouritism. Furthermore, this is probably the same thing for most of the rest.

Not only that, it would be an annoying rewrite, and we are not sure that it is strictly necessary if it is only to reproduce what we currently have with a different design.

**Comment by smorimoto** [comment]
In my very personal opinion, what this website needs is a much smaller compiler, not a massive compiler like React SSGs.

**Comment by jasonwilliams** [comment]
Fully agree with @smorimoto here.

We want to keep the site as simple as possible, many of those point seem to want to use next or react for the sake of it, despite it being a good framework it’s seems overkill for what we have right now. The static site generation works quite well for what we have, we don’t really need to build components for the moment.

> A big argument is that it is a javascript framework. Knowing that our community is around javascript it will be easy for everyone to contribute

Also, this site is already using a JavaScript framework, it’s using Eleventy.

**Comment by ctcpip** [comment]
@AugustinMauroy they are looking for help for the new node.js website (using next.js):  https://github.com/nodejs/nodejs.org/discussions/5131

edit: I see you're already involved 😆
