### ISSUE TITLE
Link to Matrix from main site.

### ISSUE THREAD

**Issue by acutmore** [tc39/tc39.github.io#329]
The TC39 matrix channel is linked to from the specification and [CONTRIBUTING.md](https://github.com/tc39/ecma262/blob/HEAD/CONTRIBUTING.md), but on https://tc39.es we seem to only link to Discourse, Github, Twitter, and Mastodon in the 'connect' section.

**Comment by smorimoto** [comment]
We have a lot of channels and I wondered which channel to link, but Spaces is defined in the specification and we have the spaces, so we can just link it. (I thought that was just an Element-specific thing until now.) https://spec.matrix.org/v1.7/client-server-api/#spaces

```
https://matrix.to/#/#tc39-space:matrix.org
```
