### ISSUE TITLE
Text should be easily updated

### ISSUE THREAD

**Issue by iddan** [tc39/tc39.github.io#4]
IMO text should be at least managed in separate, human readable documents or better in a CMS.
I had good experience with Gastby + Netlify CMS.

**Comment by codehag** [comment]
at the moment i am using jekyll, the thinking being that this way we could import existing .md files and style them for easier readability -- this means that there is less burden in keeping everything up to date, with the added benefit of not having to write html. having a cms has additional overhead

What do you think?

**Comment by iddan** [comment]
I've maintained several Jekyll sites and it was a cumbersome. Gatsby has excellent `.md` support while also providing way to define components as well as pages.

**Comment by codehag** [comment]
sure, for me the main concern is that CMS's are useful for certain types of users, but I think most users who will be working with this will find .md files easier to work with :) 

Jekyll is by no means a final decision, it was just one way to quickly prototype.

**Comment by iddan** [comment]
CMS is a overhead (even though projects like Netlify makes it much easier to maintain) but it makes editing more accessible (though one can argue the GitHub markdown editor is just fine). For the near future I think using `.md` files is just fine.

**Comment by codehag** [comment]
We do not have a need for a cms right now, so closing this
