### ISSUE TITLE
Migrate to Biome

### ISSUE THREAD

**Issue by smorimoto** [tc39/tc39.github.io#407]
https://biomejs.dev

**Comment by jasonwilliams** [comment]
Hey @smorimoto did you want to put some more meat on this? I assume this is replacing both eslint and prettier, anything else it covers?

**Comment by smorimoto** [comment]
@jasonwilliams Yeah, actually I was gonna add a little bit more context. I will write it on the aeroplane during the flight today.

**Comment by ljharb** [comment]
What's the benefit? eslint is a defacto standard, and there's not really any performance considerations in this project for linting.

**Comment by smorimoto** [comment]
I'm sorry I'm late. After all, the combination of ESLint and Prettier has some inconsistencies by default and requires some plugins to bridge the gaps, but it's important that Biome does everything well by default. I also feel that it doesn't really matter whether ESLint is the de facto standard.
