### ISSUE TITLE
Website usability thread

### ISSUE THREAD

**Issue by codehag** [tc39/tc39.github.io#41]
This issue is meant to collect usability problems that come up when people visit the site. 

If you find that you are not getting what you need from the site, please comment here and let us know what you were looking for and where you would expect to find it!

**Comment by Regaddi** [comment]
For cross-reference: #64

**Comment by lukaszsobek** [comment]
Does accessibility fall under this? If yes, which level are we aiming or A, AA or AAA?

**Comment by jasonwilliams** [comment]
I think we can close this now. If there’s a usability issue on the site please raise a new issue.
