### ISSUE TITLE
Readme page on the website, better than moving directly to the Repo

### ISSUE THREAD

**Issue by Mahmoudgalalz** [tc39/tc39.github.io#410]
I would like to add a small feature, which is remotely fetch the Readme file of each proposal to the website itself

**Comment by ljharb** [comment]
That seems like a lot of work to keep in sync. Why is that better than moving to the repo, where you're closer to filing an issue if needed?

**Comment by Mahmoudgalalz** [comment]
I guess nope, I can easily do it, by just fetching the readme data into the page for each proposal since each proposal has a README by default 

https://raw.githubusercontent.com/tc39/proposal-regex-escaping/main/README.md

for example fetch this data, adding a markdown transformer to HTML, and it can be live

**Comment by ljharb** [comment]
Right, but what's the value/benefit?

**Comment by Mahmoudgalalz** [comment]
This will support building the RSS, and its more robust we can have better features to spotlight and filter by stages and so on. See no need from it currently but I think it will has features coming later

**Comment by ljharb** [comment]
As you pointed out in #409, https://github.com/tc39/dataset already potentially covers that - we wouldn't want to use readme text as a data source.

I still don't see the benefit of duplicating the source of truth - sending someone to the repo seems strictly better to me than a webpage.

**Comment by Mahmoudgalalz** [comment]
Got your point, we can close it now 🙏
