### ISSUE TITLE
Footer with links

### ISSUE THREAD

**Issue by iddan** [tc39/tc39.github.io#5]
It's a common pattern to have a footer with all the main internal and external links of the site.

**Comment by codehag** [comment]
on this note, i like what they did here: https://webcompat.com/

**Comment by zoepage** [comment]
A footer is a great way to sum up the most important links in one spot or make specific ones to stand out. After going though the information architecture with @codehag, I am not sure if we would need it. 

The main idea right now is to group the site content in 4 links:
- TC39 (about the group itself)
- specs (how to spec etc.)
- contribution (ways to contribute)
- state of proposals (list of proposals and their state)

The site content would be under those four and if necessary supported by a dropdown sub-navigation in the main-navigation.

Which links would you see in the footer or feel like should stand out that would not fit the schema above? I definitely would add e.g. twitter / github icons in the footer.

**Comment by codehag** [comment]
@zoepage thank you so much for adding details to this!

**Comment by zoepage** [comment]
Closing as we probably will not need a footer right now. We can reopen when we need it.

**Comment by zoepage** [comment]
@iddan would you please be able to give a little bit more context here?

**Comment by iddan** [comment]
I don't understand why footer is not needed, this is a draft site but it should simulate a real site as much as possible in terms of layout

**Comment by zoepage** [comment]
Form follows function. As mentioned above we have 4 main links that group external links. The amount of the links is not verify the need of a footer, which is +7. Just having a footer for the sake of it should not be what we go for.

We can always add one as we needed as I mentioned above. Right now we want to have a stable site (MVP) that we can release, so lowest amount of features possible.

**Comment by codehag** [comment]
Ah, i thought i reviewed this on the weekend.

It looks great! thanks for all the work!
