### ISSUE TITLE
Automatically setup npm dependencies

### ISSUE THREAD

**Issue by Regaddi** [tc39/tc39.github.io#53]
We should automatically install the npm dependencies, when someone executes `make install`.
I'm not sure how to handle the case, when npm is not installed on the users machine or not the right version.
But this would automatically activate husky, lint-staged & stylelint, so we don't have to deal with code formatting in PRs.

Ideas? @codehag

**Comment by ljharb** [comment]
Why is `npm install` alone not sufficient to install all of the deps users need?

**Comment by Regaddi** [comment]
@ljharb We'd need to shift the tasks defined in the `Makefile` into the scripts part of a `package.json`. I think this wouldn't be as convenient to manage as in a JSON file. I am personally okay with having a Makefile and only have to execute `make install` to install everything. But it should also install all sub-dependencies with npm.
I am not really experienced with docker setups and not sure if this is suitable for npm in general.
