### ISSUE TITLE
Breaking the web

### ISSUE THREAD

**Issue by Ginden** [tc39/tc39.github.io#57]
This happens all the time - someone proposes breaking changes and his ideas are rejected because they break the web.

We should have authoritative document explaining **why** non-backward-compatible changes are forbidden, **when** such changes can be accepted and how one can rewrite thheir idea to make it backwards-compatible.

**Comment by Ginden** [comment]
> I feel like the meeting notes provides this kind of information.

Majority of people proposing new ideas and arguing for them don't read meeting notes (see `smoosh` issues: [flatMap/pull/56](https://github.com/tc39/proposal-flatMap/pull/56); propositions to break existing pages are heavily upvoted).

**Comment by ljharb** [comment]
Will those people read this site?

**Comment by Ginden** [comment]
We can at least send them link to such page and avoid the same discussion over and over.

**Comment by zoepage** [comment]
> don't read meeting notes

Is it possible, they just do not know where to find them?

> Will those people read this site?

I also think, its worth a shot. Especially if we are bundling information here anyway. We were thinking about adding a FAQ section (which includes a glossary and the main questions). Would this kind of information work for this content? :)

**Comment by Ginden** [comment]
> Is it possible, they just do not know where to find them?

Maybe. Though, meeting notes are big, scary and bit hermetical.

**Comment by littledan** [comment]
I think we should improve documentation there, and I disagree with the skepticism earlier in the thread about the value of such documentation. I've filed an issue in a TC39-internal repository to track our documentation effort; TC39 delegates can see it at https://github.com/tc39/how-we-work/issues/37 . I hope we can create publishable content here soon.

**Comment by xtuc** [comment]
I can see the value in documenting why TC39 would/should break the web.

It seems like @Ginden asked for a per features doc, I think this kind of information is already available in the notes or in the proposal repo. I know that both are quite verbose.

**Comment by gesa** [comment]
quick point of order on the initial issue, and sorry i didn't see this two weeks ago @Ginden,

>  one can rewrite his idea 

should be 

> one can rewrite _their_ idea 


Aside from that though I *love* this feedback, hard agree with @Ginden on meeting notes being big & scary. @zoepage My gut tells me this might deserve more space than an FAQ—especially when thinking about if we ever want to add more information after, say, a particularly contentious feature we do or do not approve. Maybe we cross that bridge when we come to it though.

**Comment by rkirsling** [comment]
> this might deserve more space than an FAQ

After #SmooshGate, this might even warrant its own cutesy PSA animation ("Hi! My name's Teecee the Toucan and I'm here to talk to you about preserving the web!"). :laughing: But yeah, maybe not for Day 1.
