### ISSUE TITLE
add information about the monthly planning call

### ISSUE THREAD

**Issue by sarahghp** [tc39/tc39.github.io#58]
What it says on the tin! Many people are unaware of the monthly planning call and that it is open to all. Let's add information about what kind of stuff is discussed and how to join.

**Comment by zoepage** [comment]
Thanks @sarahgp for the proposal. I really like it. Could you provide more information like e.g.
- date
- how to join (video link or other)
- where you can find notes?

Thanks! :)

**Comment by sarahghp** [comment]
I'm sorry — are you asking me for the information or for the categories to be included? I don't know the former (maybe @codehag or @littledan could chime in with them), which is why I think we should add them. 😸

Or is there someplace else they are posted automatically we could pull from?

For the latter, yes I'd think we'd want to include the list above, plus an agenda if there usually is one, which I am guessing is distinct from notes, which come after?

**Comment by codehag** [comment]
@zoepage @sarahgp hey you two! this is referring to our current monthly calls. They are hosted on google hangouts and the notes are here: https://docs.google.com/document/d/1KxWzOhMcAeLrvO-f9mQGGHqO4z8pe79brqUyCIqufd0/edit

the next meeting has not been scheduled yet, we should do that soon

**Comment by codehag** [comment]
Monthly call information:

10:00 AM CEST (central European time)
Last Tuesday of every month

Can be added to the readme

**Comment by littledan** [comment]
Note that notes are currently world-editable. If we share the link publicly, we should probably lock down who can edit them (or, at least regularly archive the notes).

For the call, for other meetings, I have been publicly posting my email address so people can contact me for an invite. This might prevent someone from joining in a sort of trolling way, but I am not sure if it's a real risk.

**Comment by codehag** [comment]
do we have a general email for this purpose? should we make one that moderators can have access to?

**Comment by littledan** [comment]
I just use my own for the Intl call. I think we're pretty young to set up special email addresses. No one has ever actually contacted me that way; it always ends up being that I recruit people (as you have done here).
