### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by iddan** [tc39/tc39.github.io#6]
https://developers.google.com/web/fundamentals/accessibility/

**Comment by codehag** [comment]
This is an excellent point, let's address it once we have a clearer idea of what we will be doing and start building things fully.

On this note, I would also build this page (ironically) with minimal JS unless we have something with a really special behavior / evaluation.

**Comment by codehag** [comment]
Thoughts from the docs:

- [ ] is this accessible via tab navigation? 
- [ ] Does it make sense for differently abled people?
- [ ] Do the colors pass the contrast test? Evaluate colors -- they are too pale for accessibility. We can use tools for this like the contrast checker
- [ ] investigate A11y.css
- [ ] investigate pa11y.org

**Comment by codehag** [comment]
This was taken care of by regaddi

**Comment by marcysutton** [comment]
Is there a PR or separate issue to review for accessibility concerns? I noticed the bluish-aqua links are still pretty low contrast, and they'd benefit from a more impactful color. You can check out the ratio here, it's `1.86:1` where it should be at least `4.5:1` for readability - http://contrast-ratio.com/#%2377ccbb-on-%23fefefe

Using the Chrome color picker I was able to pick a contrasting color that meets contrast guidelines: `#038067`

**Comment by codehag** [comment]
@marcysutton feel free to open another issue for this!
