### ISSUE TITLE
Icons not visible

### ISSUE THREAD

**Issue by Regaddi** [tc39/tc39.github.io#64]
When accessing the website with a bad network connection the icons are potentially invisible. The user might miss that there is a navigation icon, because the icon itself could not load.

We should provide a fallback by using native symbols.

Proposals:

Menu icon: ☰ (`&#9776;`)
Accordion caret: ▼(`&#9660;`)

Edit: they seem to be missing completely right now 🤔

Edit2:
missing on tc39.github.io/beta
visible on tc39-beta.netlify.com

**Comment by Regaddi** [comment]
OK, it's because of bad references:

![image](https://user-images.githubusercontent.com/1336590/41364643-8d0ce5f4-6f37-11e8-8fe3-06a636284020.png)

![image](https://user-images.githubusercontent.com/1336590/41364673-9bf067b2-6f37-11e8-9a87-0e81c7004bf1.png)

Path to `main.js` and `style.css` is correct, but not to `normalize.css` and `menu.svg`.
Are those paths transformed during deployment?
Would it be better to have them relative to the document?

**Comment by Regaddi** [comment]
Potentially, yes. But that won't solve the issue on `normalize.css`.
I don't understand yet, why the paths differ between both URLs. I thought they contain the same state.

**Comment by keithamus** [comment]
You can make them absolute which tends to make development across forks/repos easier:

```html
<link href="{{site.github.url}}/css/....">
```

Locally `site.github.url` is just `''`. When served through gh-pages it'll be `https://tc39.github.io/beta`, and when forked to e.g. me it'll be `https://keithamus.github.io/beta`

**Comment by keithamus** [comment]
Also while on the topic of URLs - it is preferred to avoid protocol relative URLs (that is, urls without the `http`, e.g. `src="//cdnjs.cloudflare.com..."`. This should be avoided because if you have an `https` capable asset, it should ideally always be served with `https`. (See https://www.paulirish.com/2010/the-protocol-relative-url/)

**Comment by Regaddi** [comment]
> I don't understand yet, why the paths differ between both URLs. I thought they contain the same state.

I just totally looked into the wrong file 
Thanks @keithamus!

**Comment by ljharb** [comment]
I commented on the PR, but why would we not want the paths to always be root-relative - ie, start with a `/`?

The rationale to avoid protocol-less URLs isn't that important when gh-pages, and individual sites, can be forced onto HTTPS, but it doesn't really matter either way imo.
