### ISSUE TITLE
popup layout and animation issues

### ISSUE THREAD

**Issue by r0mflip** [tc39/tc39.github.io#68]
The popup obscures the content below it even though it is hidden.

The [current implementation](https://github.com/tc39/beta/blob/65d61e221df72a92b2a79d4987135c9fd8e9243f/_sass/_popup.scss#L12-L16) for hiding it hides only the `label` using the `opacity`. The links/content underneath are still obscured by the popup preventing any interactions. The parent (`div.popup`) needs to be hidden instead of the label, which might require JS.

![image](https://user-images.githubusercontent.com/37770235/41508698-5fc61bba-7266-11e8-88e6-a38edc93298c.png)

And I would also like to mention that the keyframe `moving` has visually no effect because while the 90% mark to move the `label` is reached the label would have an opacity of `0.1` which makes it nearly invisible.

![image](https://user-images.githubusercontent.com/37770235/41508779-84546bca-7267-11e8-98ca-97c8d282e69a.png)

**Comment by othree** [comment]
I believe the visual effect for this action is fade out.
And moving is try not to cover the content of the page.
I send a PR to make this works as expect.
