### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by iddan** [tc39/tc39.github.io#7]
IMO the plain text could be spiced up with some illustrations

**Comment by codehag** [comment]
Absolutely! Am very open to suggestions!

**Comment by iddan** [comment]
Will try to make some sketches (Here are some of my previous works: https://www.instagram.com/aniddan/)
For reference I like the graphics of [Yarn](https://yarnpkg.com/lang/en/) & [NPM](https://www.npmjs.com/features)

**Comment by codehag** [comment]
I myself am partial to the graphics that the w3c has, but let's get some more feedback from others tomorrow!

**Comment by zoepage** [comment]
As we will move on with just very small changes, closing this for now. We can re-open, when we get to an iteration of the design. :)
