### ISSUE TITLE
Adding the Ecma International logo

### ISSUE THREAD

**Issue by codehag** [tc39/tc39.github.io#73]
We should think about how to place the Ecma international logo. If anyone with design experience can chime in it would be great!

Here is my haphazard attempt:

<img width="1438" alt="screen shot 2018-06-29 at 12 55 52" src="https://user-images.githubusercontent.com/26968615/42089006-e54d53aa-7b9b-11e8-8e07-3b2fdf85d028.png">

**Comment by rkirsling** [comment]
If the site had a permanent footer (to contain, say, a copyright line) then it might fit nicely down there.

**Comment by littledan** [comment]
Another option: Ecma logo on the top right?

**Comment by codehag** [comment]
This is part of the feedback from Ecma International, they find that the site makes TC39 look like a standalone committee and want the logo to be featured somewhere more prominently.  Left hand or right hand corner I think would work well for this purpose.
