### ISSUE TITLE
Making affiliation with Ecma International Clearer

### ISSUE THREAD

**Issue by codehag** [tc39/tc39.github.io#74]
We should update our text blurbs to make it clear that TC39 is not a stand alone committee, but is part of Ecma International. Here is the proposed text change:

Replace “TC39” in the following sentence with "Ecma International's TC39"

“Ecma International's TC39 is a group of JavaScript developers […]”

**Comment by rkirsling** [comment]
That blurb already ends in "We are part of Ecma International."—do you think more is still needed?

**Comment by ljharb** [comment]
I think that clarification is probably only needed once, though - just "TC39" is pretty sufficient, unless there's other well-known organizations with 39+ technical committees :-p

**Comment by serspump4299** [comment]
Like

**Comment by littledan** [comment]
I think Ecma TC39 is sufficient, and you can leave Ecma International when mentioning Ecma by itself.

**Comment by codehag** [comment]
This is a request directly from ECMA and we will need to honor it

**Comment by ljharb** [comment]
What was their exact request?

**Comment by codehag** [comment]
Replace “TC39” in the following sentence with "Ecma International's TC39"

“Ecma International's TC39 is a group of JavaScript developers […]”

They want to have that in the first sentence

**Comment by codehag** [comment]
This is one of two pieces of feedback, the other being to include the ecma logo

**Comment by codehag** [comment]
this is done.
