### ISSUE TITLE
Invited Experts:  Do's & Dont's?

### ISSUE THREAD

**Issue by ajvincent** [tc39/tc39.github.io#79]
As an invited expert to the July 2018 TC39 meeting, and someone who had never been to a TC39 meeting before, I'm relying on both discretion and gut feelings on what to do outside of the specific subject I'm speaking about.  Generally, I feel I should keep quiet, but I keep hearing ideas and proposals that I'm interested in participating in.

Mostly I'm participating via the IRC channel.

**Comment by rkirsling** [comment]
Note that each [agenda document](https://github.com/tc39/agendas/blob/master/2018/07.md) does have a link to @allenwb's [paper on committee participation](http://wirfs-brock.com/allen/files/papers/standpats-asianplop2016.pdf).

No doubt listening and IRC (and GH) communication is probably the best place to start, but if you have a substantive comment or question to add here or there, I'm sure it will be appreciated. (At least, that's been my experience so far, still being in invited expert / prospective member status myself. :smile:)

**Comment by codehag** [comment]
Should we add the paper on committee participation to the "contribute" section?

**Comment by ljharb** [comment]
@codehag it’s probably most useful for invited experts and new delegates; community members might find it interesting but not necessarily applicable?

**Comment by ctcpip** [comment]
this is covered by the `how-we-work` repo, and specifically places like https://github.com/tc39/how-we-work/blob/main/how-to-participate-in-meetings.md 

in any case, improvements, suggestions, feedback, etc should go to that repository
