### ISSUE TITLE
Launch the website?

### ISSUE THREAD

**Issue by littledan** [tc39/tc39.github.io#95]
The website looks like it's in pretty good shape. Should we launch it to `tc39.github.io`?

**Comment by xtuc** [comment]
Please note that the website includes a server-side tracker for the page viewed: https://github.com/tc39/beta/blob/49054344a33b6716ad4c29444187280c13da439a/_layouts/default.html#L43

I don't mind getting traffic on it, do we want to keep it for basic analytics or remove it?

**Comment by ljharb** [comment]
Is there a reason to use that tracker instead of something more common like Google Analytics? (we could also use both)

**Comment by xtuc** [comment]
Yes, that tracker was initially used to avoid the GDPR/EU Cookie annoyance. Using both seems a bit overkilled to me and Google Analytics is much better than just counting hits.

**Comment by ljharb** [comment]
I assume people just blindly click through that message like any TOS, but fair enough.

**Comment by littledan** [comment]
Yeah, I agree that it will be good to avoid an extra thing to click through here. Anyway, I don't see upgrading to another analytics provider as needing to block shipping. Are there other things that should block shipping?

**Comment by xtuc** [comment]
Just an idea; tc39.js.org seems available, would be better that github.io IMO.

**Comment by littledan** [comment]
We had a long discussion about the URL; it's probably worth reserving that one, but I think we'll stick with tc39.github.io.

**Comment by ljharb** [comment]
We could always make that one 301 to the GitHub one

**Comment by codehag** [comment]
I have addressed all of the comments that were raised at the meeting. Once those are merged we should be good to launch.

**Comment by xtuc** [comment]
Will the website still be considered as beta after the launch? I would be fine removing the notice, but we have multiple occurence in the project.

**Comment by codehag** [comment]
I think we should still solicit feedback, but we can stop referring to it as beta?

**Comment by xtuc** [comment]
I think it's confusing for the website to live at `tc39/beta` instead of `tc39/website` and maybe we could rephrease the banner to remove the beta mention?

**Comment by littledan** [comment]
@xtuc The idea is to have it at `tc39.github.io`; I'm not sure why we'd put it at `/website`.

**Comment by xtuc** [comment]
Yes, sorry I meant this repository: https://github.com/tc39/beta. We could rename it to https://github.com/tc39/website.

Then we can redirect `tc39.github.io` to https://github.com/tc39/website, right?

**Comment by codehag** [comment]
This has been launched (for a while now!)
